### ISSUE TITLE
CRA

### ISSUE THREAD

**Issue by crrmacarse** [jedrobado/myfirstreact#1]
CRA(create-react-app) ni tol bale boilerplate mismo from react. limited ka lang sa mga commands pero may option kman mag eject. Kung la kapa syado experience sa react ky di lang danay mag eject.

Regarding sa live-server ky no need na ina. npm start ky gina auto-refresh nya naman dayon kung may mga changes ka sa source files mo:
https://stackoverflow.com/questions/43274925/development-server-of-create-react-app-does-not-auto-refresh

**Comment by jedrobado** [comment]
react-scripts eject? Ano sa ang eject?

**Comment by crrmacarse** [comment]
Ma detach ang webpack tas mga pre-made configs. kumbaga ang idea sg create-react-app dan is ma limit ang mga newcomer sa pag config pa prior mag start sg frontend development sa node.

https://medium.com/curated-by-versett/dont-eject-your-create-react-app-b123c5247741

**Comment by crrmacarse** [comment]
tutal first timer ka palang sa react ky amo na ang advisable path. lagaw2 lang danay tas once confident kana ky detach mo(preferably sa next project mo nalang).

example sg from scratch implementation sg react ky ang portfolio repo ko:
https://github.com/crrmacarse/crrmacarse.github.io
